[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra -q"
testpaths = ["tests"]

[tool.black]
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | data
  | .venv
  | migrations
)
'''

[tool.isort]
profile = "black"
py_version = 310
skip_gitignore = true