"""empty message

Revision ID: 30baba02c953
Revises: 
Create Date: 2024-11-17 18:03:37.573323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30baba02c953'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Date(), nullable=False),
    sa.Column('report', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='0', nullable=True),
    sa.Column('price', sa.Float(), server_default='0', nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['sale_id'], ['sale.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'sale_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    op.drop_table('sale')
    # ### end Alembic commands ###
